# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Windowrules Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Windows Rules https://wiki.hyprland.org/0.45.0/Configuring/Window-Rules/ #

# ======= Window Rules =======
# Default workspaces for programs
windowrule = match:class Spotify, workspace 2
windowrule = match:class Docker Desktop, workspace 3
windowrule = match:class DBeaver, workspace 8
windowrule = match:class obsidian, workspace special:obsidian

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    # Hyprland-run windowrule
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = picture-in-picture
    match:title = ^(Picture-in-Picture)$
    float = yes
    size = 960 540
    move = 25%-
}

windowrule {
    name = opacity-overrides
    match:class = (zen|firefox|krita)
    opacity = 1 override 1 override
}

windowrule {
    name = general-rules
    match:title = ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
    float = yes
    move = 25%-
    size = 960 540
}

# Float Necessary Windows
windowrule = match:class org.pulseaudio.pavucontrol, move onscreen cursor
windowrule = match:class ^(org.pulseaudio.pavucontrol), float true
windowrule = match:class ^()$, match:title ^(Picture in picture)$, float true
windowrule = match:class ^()$, match:title ^(Save File)$, float true
windowrule = match:class ^()$, match:title ^(Open File)$, float true
windowrule = match:class ^(LibreWolf)$, match:title ^(Picture-in-Picture)$, float true
windowrule = match:class ^(blueman-manager)$, float true
windowrule = match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$, float true
windowrule = match:class ^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$, float true
windowrule = match:class ^(CachyOSHello)$, float true
windowrule = match:class ^(zenity)$, float true
windowrule = match:class ^()$, match:title ^(Steam - Self Updater)$, float true

# General window rules
windowrule = match:title ^(danmufloat)$, pin yes
windowrule = match:title ^(danmufloat|termfloat)$, rounding 5

# Decorations related to floating windows on workspaces 1 to 10
# TODO: Fix these. Check latest CachyOS config for hyprland
# windowrule = bordersize 2, floating:1, onworkspace:w[fv1-10]
# windowrule = bordercolor $cachylblue, floating:1, onworkspace:w[fv1-10]
# windowrule = rounding 8, floating:1, onworkspace:w[fv1-10]
# Decorations related to tiling windows on workspaces 1 to 10
# windowrule = bordersize 3, floating:0, onworkspace:f[1-10]
# windowrule = rounding 4, floating:0, onworkspace:f[1-10]

# ======= Workspace Rules =======
# Workspaces assigned to monitors
workspace = 1, monitor:DP-4, default:true
workspace = 2, monitor:DP-4
workspace = 3, monitor:DP-4
workspace = 4, monitor:DP-4
workspace = 5, monitor:DP-4
workspace = 6, monitor:DP-5, default:true
workspace = 7, monitor:DP-5
workspace = 8, monitor:DP-5
workspace = 9, monitor:DP-5
workspace = 10, monitor:DP-5

workspace = special:notes, on-created-empty:export NVIM_APPNAME="kickstart.nvim"; alacritty --working-directory ~/notes -e nvim "Notes/Index - Work.md"

workspace = w[tv1-10], gapsout:5, gapsin:3
workspace = f[1], gapsout:5, gapsin:3

# ======= Layer Rules =======
# layerrule = animation slide top, logout_dialog
# layerrule = animation popin 50%, waybar
# layerrule = animation slide down, waybar
# layerrule = animation fade 50%, wallpaper
