
[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_title = true

[window.padding]
x = 7
y = 7

[general]
import = [
    "~/.config/alacritty/fonts.toml",
    "~/.config/alacritty/colours/catpuccin.toml"
]
