$file = $HOME/Pictures/aesthetic-wallpapers/images/tree-house.png
preload = $file

wallpaper {
    monitor = DP-4
    path = $file
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = $file
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = $HOME/Pictures/aesthetic-wallpapers/images/tree-house.png
    fit_mode = cover
}
