import = [
    "~/.config/alacritty/fonts.toml",
    "~/.config/alacritty/colours/catpuccin.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_title = true

[window.padding]
x = 8
y = 8
