import = [
    "~/.config/alacritty/fonts.toml",
    "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0

[window.padding]
x = 5
y = 5
